#!/usr/bin/env python3
"""§6.6.3: regenerate `docs/asm/` and, on demand, diff it.

    bench/isa/dump_asm.py            regenerate docs/asm/
    bench/isa/dump_asm.py --check    fail if the checked-in asm is stale

The spec's requirement:

    "Disassembly of each hot loop is checked into docs/asm/ and diffed in CI.
     A silent change in vectorisation is a regression even if the wall-clock
     didn't move on the current host."

This was 123 lines of bash wrapped around an embedded awk program that split
objdump output per symbol, plus seven `grep -c` calls per kernel to count
instruction families. Counting instructions is data processing, and awk inside
bash inside a heredoc is where that stops being reviewable: the symbol-splitting
rule and the counting rules lived in two different languages, neither of which
could be unit-tested.

Requires `zig build bench-isa` to have run first.

Stdlib only. This runs on a fresh clone before `uv sync` has necessarily
happened, so it must not need `bench/.venv`.
"""

from __future__ import annotations

import argparse
import difflib
import os
import re
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(os.environ.get("STRAWMANN_ROOT", Path(__file__).resolve().parents[2]))
ISA_DIR = ROOT / "zig-out/isa"
OUT_DIR = ROOT / "docs/asm"

#: The kernels exported by `bench/isa/asm_probe.zig`.
KERNELS = ("sm_dot_f32", "sm_euclid_f32", "sm_manhattan_f32", "sm_dot_u8i8",
           "sm_dot_u8u8", "sm_dot_f32u8", "sm_hamming")

#: Instruction families the §6.6.2 claims rest on. A zero where a nonzero is
#: expected is the §11 "LLVM quietly split the op" failure, visible here and
#: nowhere else.
COUNTS = ("zmm", "ymm", "vpdpbusd", "vpopcnt", "vpshufb", "vfmadd")

#: objdump symbol header: `0000000000001234 <sm_dot_f32>:`
SYMBOL = re.compile(r"^[0-9a-f]+ <(?P<name>.+)>:$")
#: Leading `  1234:\t` address column, stripped for the same reason as raw
#: bytes: it changes with every relocation and makes the diff pure noise.
ADDRESS = re.compile(r"^\s*[0-9a-f]+:\s*")


@dataclass
class Kernel:
    arm: str
    name: str
    lines: list[str]

    def count(self, needle: str) -> int:
        return sum(1 for ln in self.lines if needle in ln)


def disassemble(binary: Path, objdump: str) -> str:
    """--no-show-raw-insn drops encoded bytes; -M intel because the spec names
    instructions in Intel syntax (vpdpbusd, vpopcntq, vpshufb)."""
    r = subprocess.run([objdump, "-d", "--no-show-raw-insn", "-M", "intel", str(binary)],
                       capture_output=True, text=True)
    if r.returncode != 0:
        raise SystemExit(f"{objdump} failed on {binary}:\n{r.stderr.strip()}")
    return r.stdout


def split_symbols(text: str, arm: str) -> list[Kernel]:
    """One disassembly pass per binary, split per symbol of interest."""
    want = set(KERNELS)
    out: list[Kernel] = []
    cur: Kernel | None = None
    for raw in text.splitlines():
        m = SYMBOL.match(raw.strip())
        if m:
            name = m.group("name")
            cur = Kernel(arm, name, []) if name in want else None
            if cur:
                out.append(cur)
            continue
        if cur is None:
            continue
        line = ADDRESS.sub("", raw).rstrip()
        if line:
            cur.lines.append(line)
    return out


def summary(kernels: list[Kernel]) -> str:
    """Emitted-instruction counts per (arm, kernel).

    This table is the check that caught `prefer_256_bit` silently capping the
    AVX-512 arms at 256-bit width: every arm benchmarked differently while the
    zmm column read 0 across the board.
    """
    head = ["# Emitted-instruction summary per ISA arm", "",
            "Generated by `bench/isa/dump_asm.py`. One row per (arm, kernel).", "",
            "`zmm` counts confirm 512-bit width; `vpdpbusd` and `vpopcntq` counts",
            "confirm the §6.6.2 instruction claims. A zero where a nonzero is",
            'expected is the §11 "LLVM quietly split the op" failure, visible here',
            "and nowhere else.", "",
            "| arm | kernel | insns | " + " | ".join(COUNTS) + " |",
            "|---|---|--:|" + "--:|" * len(COUNTS)]
    for k in sorted(kernels, key=lambda k: (k.arm, KERNELS.index(k.name))):
        cells = [str(k.count(c)) for c in COUNTS]
        head.append(f"| {k.arm} | {k.name} | {len(k.lines)} | " + " | ".join(cells) + " |")
    return "\n".join(head) + "\n"


def build(staging: Path, objdump: str) -> list[Kernel]:
    if not ISA_DIR.is_dir():
        raise SystemExit(f"{ISA_DIR} not found; run 'zig build bench-isa' first")
    all_kernels: list[Kernel] = []
    for arm_dir in sorted(p for p in ISA_DIR.iterdir() if p.is_dir()):
        arm = arm_dir.name
        probe = arm_dir / f"asm-probe-{arm}"
        if not (probe.exists() and os.access(probe, os.X_OK)):
            continue
        kernels = split_symbols(disassemble(probe, objdump), arm)
        (staging / arm).mkdir(parents=True, exist_ok=True)
        for k in kernels:
            (staging / arm / f"{k.name}.asm").write_text("\n".join(k.lines) + "\n")
        all_kernels.extend(kernels)
    if not all_kernels:
        raise SystemExit(f"no asm-probe binaries under {ISA_DIR}; run 'zig build bench-isa'")
    (staging / "SUMMARY.md").write_text(summary(all_kernels))
    return all_kernels


def tree(root: Path) -> dict[str, str]:
    return {str(p.relative_to(root)): p.read_text()
            for p in sorted(root.rglob("*")) if p.is_file()}


def diff_trees(old: Path, new: Path) -> list[str]:
    a, b = tree(old), tree(new)
    out: list[str] = []
    for name in sorted(set(a) | set(b)):
        if name not in a:
            out.append(f"+++ new file: {name}")
        elif name not in b:
            out.append(f"--- removed: {name}")
        elif a[name] != b[name]:
            out.extend(difflib.unified_diff(
                a[name].splitlines(), b[name].splitlines(),
                fromfile=f"docs/asm/{name}", tofile=f"regenerated/{name}",
                lineterm="", n=2))
    return out


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description="Regenerate or check docs/asm/.")
    ap.add_argument("--check", action="store_true",
                    help="fail if the checked-in asm is stale, changing nothing")
    args = ap.parse_args(argv[1:])

    objdump = os.environ.get("OBJDUMP", "objdump")
    if not shutil.which(objdump):
        raise SystemExit(f"{objdump} not found (set OBJDUMP to override)")

    with tempfile.TemporaryDirectory() as td:
        staging = Path(td)
        kernels = build(staging, objdump)

        if args.check:
            if not OUT_DIR.exists():
                print(f"error: {OUT_DIR} does not exist; run without --check",
                      file=sys.stderr)
                return 1
            d = diff_trees(OUT_DIR, staging)
            if d:
                print("error: docs/asm/ is stale, vectorisation changed.", file=sys.stderr)
                print("Review the diff, then run 'zig build asm' to accept it.\n",
                      file=sys.stderr)
                print("\n".join(d[:200]), file=sys.stderr)
                return 1
            print(f"docs/asm/ is up to date ({len(kernels)} kernels).")
            return 0

        if OUT_DIR.exists():
            shutil.rmtree(OUT_DIR)
        shutil.copytree(staging, OUT_DIR)
        arms = sorted({k.arm for k in kernels})
        print(f"wrote {OUT_DIR}: {len(arms)} arms, {len(kernels)} kernels\n")
        print((OUT_DIR / "SUMMARY.md").read_text())
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
