#!/usr/bin/env python3
"""Fixtures the harness tests share: a temp result tree, and rows to fill it.

Split out of `test_harness.py`, which had grown to 3,201 lines and 147 tests
across five subjects that share nothing but these. A failure in it named a line
number in a file too large to hold in one's head.
"""

from __future__ import annotations

import importlib
import importlib.util
import json
import os
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE.parent))  # bench/setup.py, for its foreign-load rule

from workloads import stamp_hash  # noqa: E402  (pure; no ROOT involved)


def _reload(root: Path):
    """Point the harness modules at `root` and reload them in dependency order."""
    os.environ["STRAWMANN_ROOT"] = str(root)
    mods = {}
    # `report_data` before `report`: it resolves ROOT at import and `report`
    # imports its names, so reloading only the latter leaves the loading layer
    # pointed at the real checkout while the tests write into a temp root.
    for name in ("procstat", "provenance", "workloads", "recall", "regression", "compare",
                 "report_data"):
        if name in sys.modules:
            mods[name] = importlib.reload(sys.modules[name])
        else:
            mods[name] = importlib.import_module(name)
    return mods


#: Every fixture row is stamped as measured by `good_stamp()` at `-n 50000`
#: unless a test says otherwise; `stamp=None` leaves the row unstamped.
N = 50_000


def _row(wid: str, qps: float | None, ef: int | None = 128, collection: str = "bench2",
         load_mode: str = "closed-loop", stamp: dict | str | None = "default",
         n: int | None = N, **extra) -> dict:
    r = {"id": wid, "status": "ok", "seconds": 3, "load_start": 0, "load_end": 0,
         "foreign": "", "qps": qps, "rps": qps, "detail": "", "when": "2026-01-01T00:00:00Z",
         "load_mode": load_mode, "latency": {}, "ef": ef, "collection": collection,
         "recall_joinable": True, "notes": "", "n_requested": n}
    if stamp == "default":
        stamp = good_stamp()
    if stamp is not None:
        r["harness_hash"] = stamp_hash(stamp)
    r.update(extra)
    return r


def _sweep(collection: str, dataset: str, recall_at_128: float, **extra) -> dict:
    d = {"label": "x", "collection": collection, "dataset": dataset, "metric": "euclid",
         "base_checksum": "7bf7", "queries": 2000,
         "points": [{"ef": 128, "exact": False, "recall_at_1": 0.9,
                     "recall_at_10": recall_at_128, "smoke_qps": 1.0}]}
    d.update(extra)
    return d


#: What `provenance.collect` stamps `run.json` with: when the arm started, UTC
#: ISO 8601. Fixed rather than `now`, because `report.default_out` keys the
#: report's file name by it and a name that moves with the clock cannot be
#: asserted on. Override per label to build a run measured on another day.
STARTED = "2026-08-20T09:00:00Z"


class Fixture:
    """A pair of result directories under a temporary root."""

    def __init__(self, tmp: Path):
        self.root = tmp
        (tmp / "bench/results").mkdir(parents=True)
        # compare.py splices into these when asked; markers only.
        (tmp / "README.md").write_text(
            "x\n<!-- BEGIN compare-table (generated by bench/harness/compare.py --write-readme) -->\n"
            "old\n<!-- END compare-table -->\ny\n")
        (tmp / "docs").mkdir()
        # Each dataset's table lives in its own `docs/comparison-<dataset>.md`,
        # which compare.py creates on the first run that renders that dataset.

    def label(self, name: str, rows: list[dict], stamp: dict | None,
              conformance: dict | None = None, sweeps: list[tuple[str, dict]] = (),
              dataset: str = "sift1m", started: str = STARTED,
              collections: list[dict] | None = None) -> Path:
        d = self.root / "bench/results" / name
        d.mkdir(parents=True, exist_ok=True)
        (d / "rows.json").write_text(json.dumps(rows))
        meta = {"label": name, "dataset": {"name": dataset}, "started": started,
                "upload_n": 1_000_000,
                "queries": 50_000, "gate": "FAIL", "host": {"hostname": "h", "cpu": "c"}}
        if stamp is not None:
            meta["harness"] = stamp
        (d / "run.json").write_text(json.dumps(meta))
        if conformance is not None:
            (d / "conformance.json").write_text(json.dumps(conformance))
        elif (d / "conformance.json").exists():
            (d / "conformance.json").unlink()
        # What `fullrun.capture_collections` reads back off the engine. Absent
        # unless a test asks for it, which is itself a case under test: a row
        # whose index state was never read back is not a row whose index
        # existed.
        if collections is not None:
            (d / "collections.json").write_text(
                json.dumps({"label": name, "collections": collections}))
        for fname, sweep in sweeps:
            (d / fname).write_text(json.dumps(sweep))
        return d


def good_stamp(**over) -> dict:
    s = {"commit": "abc", "metric": "Euclid", "query_source": {"W3": "dataset:from-start"},
         "upload_n": 1_000_000, "w11_n": 200_000, "queries": 50_000, "exact_queries": 2000,
         "collection": {"segments": 1, "indexing_threshold_kb": 1000},
         "ef": {"W3": 128}, "bfb_pin": "dev @ 8b6dec0a"}
    s.update(over)
    return s


CONF_T3 = {"hash": "h1", "tier_reached": "T3", "licenses_perf": True,
           "licenses_comparative": True}
CONF_T2 = {"hash": "h1", "tier_reached": "T2", "licenses_perf": True,
           "licenses_comparative": False}

#: A stand-in bfb, used by the workload tests and by anything that needs a
#: row to have taken measurable time. It sat between two test classes in the
#: single-file suite; it is a fixture, so it lives with the fixtures.
FAKE_BFB = '#!/usr/bin/env python3\n"""A stand-in bfb: writes the JSON the harness reads, and takes its time.\n\nThe concurrent append (`--skip-create`) finishes in 0.1 s; a search runs 0.5 s\nand reports 100 requests, so W11\'s overlap is a fifth of the row.\n"""\nimport json, sys, time\nargv = sys.argv[1:]\nout = argv[argv.index("--json") + 1]\nif "--skip-create" in argv:\n    time.sleep(0.1)\n    json.dump({"results": {"upload": {"points_per_sec": 1000.0, "duration_secs": 0.1}}},\n              open(out, "w"))\nelse:\n    time.sleep(0.5)\n    json.dump({"config": {"collection_name": "bench2"},\n               "results": {"search": {"duration_secs": 0.5, "full_timings": [0.001] * 100,\n                                      "server_timings": [0.0005] * 100}}}, open(out, "w"))\n    print("Median qps: 200.0\\nMedian rps: 200.0")\n'
