#!/usr/bin/env python3
"""The landing page's report cards, generated from the archived pages.

    landing_cards.py            splice the cards into docs/index.html
    landing_cards.py --check    gate step: fail if the cards are not current

One card per `docs/reports/report-*.html`, built from what that page says
about itself: its dataset, its licence banner, its equal-recall verdict and its
pass count. The cards were written by hand, and a page added or retired left
them describing the archive as it was. The source is the committed pages
rather than `bench/results/`, which is gitignored, so CI can check them.

Stdlib only: the gate runs this under whatever interpreter it has.
"""

from __future__ import annotations

import html
import re
import sys
from pathlib import Path
from typing import NamedTuple

ROOT = Path(__file__).resolve().parents[2]
REPORTS = ROOT / "docs/reports"
PAGE = ROOT / "docs/index.html"
BEGIN = "<!-- BEGIN landing-reports (generated by bench/harness/landing_cards.py) -->"
END = "<!-- END landing-reports -->"

#: `report.default_out`'s naming: report-<dataset>-<a>-vs-<b>-<day>-<hhmm>.html.
NAME = re.compile(r"^report-(?P<rest>.+)-(?P<day>\d{4}-\d{2}-\d{2})-(?P<hhmm>\d{4})\.html$")


class Card(NamedTuple):
    file: str
    dataset: str
    labels: str
    measured: str  # "2026-09-25 20:21", from the file name, sortable
    tier: str | None
    gated: bool
    passes: int | None
    verdict: str | None


def text_of(fragment: str) -> str:
    """A fragment of the page as one line of plain text."""
    return " ".join(html.unescape(re.sub(r"<[^>]+>", " ", fragment)).split())


def parse(name: str, page: str) -> Card | None:
    """What one archived page says about itself, or `None` for a file that
    is not named like a report page.

    Each field is read from a sentence `templates/report.html.j2` writes, and
    is `None` when the page does not carry it: a card with a missing chip is
    still a correct card, and a crash would take the gate step with it.
    """
    m = NAME.match(name)
    if not m:
        return None
    ds = re.search(r"<dt>Dataset</dt><dd>(.*?)</dd>", page, re.DOTALL)
    dataset = text_of(ds.group(1)) if ds else ""
    rest = m["rest"]
    if dataset and rest.startswith(dataset + "-"):
        rest = rest[len(dataset) + 1:]
    labels = rest.replace("-vs-", " vs ", 1)
    banner = re.search(r'id="verdict">(.*?)</div>', page, re.DOTALL)
    banner_text = text_of(banner.group(1)) if banner else ""
    tier = re.search(r"Conformance passed through tier (T\d)", banner_text)
    passes = re.search(r"Every figure is the median of (\d+) passes", page)
    verdict = re.search(r'<p class="verdict">(.*?)</p>', page, re.DOTALL)
    return Card(
        file=name, dataset=dataset or "unknown", labels=labels,
        measured=f"{m['day']} {m['hhmm'][:2]}:{m['hhmm'][2:]}",
        tier=tier.group(1) if tier else None,
        gated=banner_text.startswith("Host gate passed"),
        passes=int(passes.group(1)) if passes else None,
        verdict=text_of(verdict.group(1)) if verdict else None)


def cards(reports: Path | None = None) -> list[Card]:
    out = []
    for p in sorted((reports or REPORTS).glob("report-*.html")):
        c = parse(p.name, p.read_text(errors="replace"))
        if c:
            out.append(c)
    return out


def render(cs: list[Card]) -> str:
    """The cards, newest first, with each dataset's newest page marked current."""
    newest = {}
    for c in cs:
        if c.measured > newest.get(c.dataset, ""):
            newest[c.dataset] = c.measured
    lines = ['<div class="cards">']
    for c in sorted(cs, key=lambda c: c.measured, reverse=True):
        chips = []
        if newest[c.dataset] == c.measured:
            chips.append('<span class="chip now">current</span>')
        if c.tier:
            chips.append(f'<span class="chip">{html.escape(c.tier)}</span>')
        chips.append('<span class="chip">gate pass</span>' if c.gated else
                     '<span class="chip bad">development-grade</span>')
        if c.passes:
            chips.append(f'<span class="chip">{c.passes} pass{"es" if c.passes > 1 else ""}</span>')
        lines += ['  <article class="card">',
                  '    <div class="card-top">',
                  (f'      <a href="reports/{html.escape(c.file)}">{html.escape(c.dataset)}, measured '
                   f'{html.escape(c.measured)}</a>'),
                  f"      {''.join(chips)}",
                  "    </div>",
                  f"    <p><code>{html.escape(c.labels)}</code></p>"]
        if c.verdict:
            lines.append(f"    <p>{html.escape(c.verdict)}</p>")
        lines.append("  </article>")
    lines.append("</div>")
    return "\n".join(lines)


def splice(page: str, block: str) -> str:
    if page.count(BEGIN) != 1 or page.count(END) != 1:
        raise ValueError(f"{PAGE.name} needs exactly one {BEGIN} / {END} pair")
    head, rest = page.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    return f"{head}{BEGIN}\n{block}\n{END}{tail}"


def main(argv: list[str]) -> int:
    check = "--check" in argv[1:]
    page = PAGE.read_text()
    try:
        new = splice(page, render(cards()))
    except ValueError as e:
        print(e, file=sys.stderr)
        return 1
    if new == page:
        print(f"ok: {PAGE.relative_to(ROOT)}'s report cards match docs/reports/")
        return 0
    if check:
        print(f"{PAGE.relative_to(ROOT)}'s report cards do not match docs/reports/.\n"
              f"Run: bench/harness/landing_cards.py", file=sys.stderr)
        return 1
    PAGE.write_text(new)
    print(f"{PAGE.relative_to(ROOT)}: report cards updated")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
